### PR TITLE
Update FedACHdir.txt url

### PR DESCRIPTION
**Pull request by codebender**
The URL was changed by "the fed" again, so I updated that url and the data/FedACHdir.txt file

:smile_cat:

### CODE REVIEW

**Comment by mgreensmith** [comment]
Thanks for this PR!

Were you able to successfully download the text file from the new URL via this utility? The new URL appears to be protected by a redirect that forces you to agree to a TOU, sets a session cookie and then redirects you to the actual file.

**Comment by codebender** [comment]
oh dang, I was just about to start using the updated url. Any ideas on how to get it working with the new URL?

**Comment by mgreensmith** [comment]
I don't have an easy way to fake out the session with the Fed, but someone else has. We found a mirror of the data available at https://github.com/gatepay/fedachdir (raw file at [1]), and we've been fetching the content from there. I guess I'm OK with making that the canonical source URL for this tool. Want to update the link?

[1] https://raw.githubusercontent.com/gatepay/FedACHdir/master/FedACHdir.txt

**Comment by codebender** [comment]
I would set it to https://raw.githubusercontent.com/gatepay/FedACHdir/master/FedACHdir.txt, if the repo owner didn't say "DO NOT DOWNLOAD THE RAW DATA FROM HERE."

I think I found out how to fake out the fed session. We do a POST to https://www.frbservices.org/EPaymentsDirectory/submitAgreement with data agreementValue=Agree,  then get back a JSESSIONID,  we then set that cookie for our GET of the FedACHdir.txt file.  This worked just using curls. I'll get this working in the gem :raised_hands:

**Comment by codebender** [comment]
@mgreensmith I got it working:

irb(main):001:0> RoutingNumber.get(121000358)
I, [2015-04-16T12:42:30.486760 #32881]  INFO -- : Connecting to Redis.
D, [2015-04-16T12:42:30.486857 #32881] DEBUG -- : Connection settings: {:db=>15}
I, [2015-04-16T12:42:30.493371 #32881]  INFO -- : Loading routing numbers...
I, [2015-04-16T12:42:30.493444 #32881]  INFO -- : Getting new bank routing data from: https://www.frbservices.org/EPaymentsDirectory/FedACHdir.txt
ETHON: Libcurl initialized
ETHON: performed EASY effective_url=https://www.frbservices.org/EPaymentsDirectory/submitAgreement response_code=302 return_code=ok total_time=1.111377
ETHON: performed EASY effective_url=https://www.frbservices.org/EPaymentsDirectory/FedACHdir.txt response_code=200 return_code=ok total_time=2.708306
  19602 loaded (2.58 seconds ~ 7607/sec)
I, [2015-04-16T12:42:37.085239 #32881]  INFO -- : Done loading routing numbers.
=> {:office_code=>"O", :servicing_frb_number=>"121000374", :record_type_code=>"1", :change_date=>"101310", :new_routing_number=>"", :name=>"Bank of America", :address=>"8001 VILLA PARK DRIVE", :city=>"HENRICO", :state=>"VA", :institution_status_code=>"1", :data_view_code=>"1", :filler=>"", :zip=>"23228", :phone=>"800-446-0135", :routing_number=>121000358}

**Comment by mgreensmith** [comment]
Thanks for all this work @codebender!

**Pull request merged**
